# Generated by Django 6.0.5 on 2026-05-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='城市名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='城市编号')),
            ],
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='机房名称')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenters', to='hosts.city', verbose_name='所在城市')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('encrypted_password', models.BinaryField(blank=True, null=True, verbose_name='加密后的ROOT密码')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='hosts.city', verbose_name='所在城市')),
                ('datacenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='hosts.datacenter', verbose_name='所在机房')),
            ],
        ),
        migrations.CreateModel(
            name='HostDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('host_count', models.PositiveIntegerField(default=0, verbose_name='主机数量')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.city', verbose_name='城市')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.datacenter', verbose_name='机房')),
            ],
            options={
                'verbose_name': '主机日统计',
                'unique_together': {('date', 'city', 'datacenter')},
            },
        ),
    ]
