# Generated by Django 6.0.5 on 2026-05-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_alter_host_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostdailystat',
            options={'verbose_name': '主机日统计', 'verbose_name_plural': '主机日统计'},
        ),
    ]
