# Generated by Django 6.0.5 on 2026-05-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_alter_hostdailystat_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='city',
        ),
    ]
