# Generated by Django 6.0.5 on 2026-05-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_remove_host_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostdailystat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='hostdailystat',
            constraint=models.UniqueConstraint(fields=('date', 'city', 'datacenter'), name='unique_daily_datacenter'),
        ),
    ]
