# Generated by Django 6.0.5 on 2026-05-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_alter_hostdailystat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hostdailystat',
            name='unique_daily_datacenter',
        ),
        migrations.AddConstraint(
            model_name='hostdailystat',
            constraint=models.UniqueConstraint(fields=('date', 'city', 'datacenter'), name='unique_daily_stat'),
        ),
    ]
